language: php

php:
  - 7.2
  - 7.3
  - 7.4
  - nightly

cache:
  directories:
    - ~/.cache/composer

matrix:
  fast_finish: true
  allow_failures:
    - php: nightly

before_install:
  - phpenv config-rm xdebug.ini
  - alias composer=composer\ --no-interaction && composer selfupdate
  - composer global require hirak/prestissimo

install:
  - travis_retry composer update --no-progress --profile --no-scripts --no-suggest $DEPENDENCIES

script:
  - vendor/bin/grumphp run
